workflows:
  build_apk:
    name: Build Flutter APK (Optimized)
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build APK (split per ABI)
        script: flutter build apk --release --split-per-abi

    artifacts:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - build/app/outputs/flutter-apk/app-x86_64-release.apk