// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4LZWn9MbuVR67IroWlMaxV1PCIEWGsPg',
    appId: '1:904195856271:web:ef9bf088f99aff88035dfa',
    messagingSenderId: '904195856271',
    projectId: 'abdullahabdullah',
    authDomain: 'abdullahabdullah.firebaseapp.com',
    storageBucket: 'abdullahabdullah.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALmc_EdO6vB810I5g1LZHhN5_z9QNz_kA',
    appId: '1:904195856271:android:bb7a65c499b604da035dfa',
    messagingSenderId: '904195856271',
    projectId: 'abdullahabdullah',
    storageBucket: 'abdullahabdullah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdjv354t5Czu-vP-_jDddzJEqJ8YL3mxc',
    appId: '1:904195856271:ios:a3d4f7a6cca7c947035dfa',
    messagingSenderId: '904195856271',
    projectId: 'abdullahabdullah',
    storageBucket: 'abdullahabdullah.firebasestorage.app',
    iosBundleId: 'com.example.abdullahNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdjv354t5Czu-vP-_jDddzJEqJ8YL3mxc',
    appId: '1:904195856271:ios:a3d4f7a6cca7c947035dfa',
    messagingSenderId: '904195856271',
    projectId: 'abdullahabdullah',
    storageBucket: 'abdullahabdullah.firebasestorage.app',
    iosBundleId: 'com.example.abdullahNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4LZWn9MbuVR67IroWlMaxV1PCIEWGsPg',
    appId: '1:904195856271:web:03fdc0fd67c57fae035dfa',
    messagingSenderId: '904195856271',
    projectId: 'abdullahabdullah',
    authDomain: 'abdullahabdullah.firebaseapp.com',
    storageBucket: 'abdullahabdullah.firebasestorage.app',
  );
}
